### ISSUE TITLE
Easier possibility to rename with changing the file type.

### ISSUE THREAD

**Issue by schvabodka-man** [jhotmann/node-rename-cli#5] opened 2017-07-29 13:51 UTC
Hi. That would be nice if i can rename the file "as is". For example. Now i'f i'm trying to do this
rename file.cfg file.txt i'm getting error and i need to do a lot of things to just change the file type.  That would be nice if app will not crash if i'm attempting to do that and i can just rename file.cfg to file.txt easy and without any other operations.

**Comment by jhotmann** [comment] 2017-07-30 18:47
I could not reproduce this on MacOS.  What platform are you on and can you post the error text?

**Comment by schvabodka-man** [comment] 2017-08-02 09:04
Linux, Fedora 25. But funny how i can't recreate this error again. Everything works ok now, but there is definitely some bug.

**Comment by jhotmann** [comment] 2018-04-12 03:02
Closing until it can be reproduced

**Closed by jhotmann** 2018-04-12 03:02 UTC
